In [14]:
import pandas as pd
import numpy as np

#### Question 1: Version of Pandas

In [4]:
pd.__version__

'2.1.0'

In [5]:
!! wget https://raw.githubusercontent.com/alexeygrigorev/datasets/master/housing.csv

['--2023-09-19 14:22:57--  https://raw.githubusercontent.com/alexeygrigorev/datasets/master/housing.csv',
 'Resolving raw.githubusercontent.com (raw.githubusercontent.com)... ::ffff:185.199.111.133, ::ffff:185.199.108.133, ::ffff:185.199.109.133, ...',
 'Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|::ffff:185.199.111.133|:443... connected.',
 'HTTP request sent, awaiting response... 200 OK',
 'Length: 1423529 (1.4M) [text/plain]',
 'Saving to: ‘housing.csv’',
 '',
 '     0K .......... .......... .......... .......... ..........  3% 3.32M 0s',
 '    50K .......... .......... .......... .......... ..........  7% 4.64M 0s',
 '   100K .......... .......... .......... .......... .......... 10% 2.30M 0s',
 '   150K .......... .......... .......... .......... .......... 14% 4.41M 0s',
 '   200K .......... .......... .......... .......... .......... 17% 3.19M 0s',
 '   250K .......... .......... .......... .......... .......... 21% 5.27M 0s',
 '   300K .......... .......

#### Question 2: Number of columns in the dataset
10 columns

In [7]:
df = pd.read_csv('housing.csv')
df

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0        -122.23     37.88                41.0        880.0           129.0   
1        -122.22     37.86                21.0       7099.0          1106.0   
2        -122.24     37.85                52.0       1467.0           190.0   
3        -122.25     37.85                52.0       1274.0           235.0   
4        -122.25     37.85                52.0       1627.0           280.0   
...          ...       ...                 ...          ...             ...   
20635    -121.09     39.48                25.0       1665.0           374.0   
20636    -121.21     39.49                18.0        697.0           150.0   
20637    -121.22     39.43                17.0       2254.0           485.0   
20638    -121.32     39.43                18.0       1860.0           409.0   
20639    -121.24     39.37                16.0       2785.0           616.0   

       population  households  median_income  median_house_value  \
0           322.0       126.0         8.3252            452600.0   
1          2401.0      1138.0         8.3014            358500.0   
2           496.0       177.0         7.2574            352100.0   
3           558.0       219.0         5.6431            341300.0   
4           565.0       259.0         3.8462            342200.0   
...           ...         ...            ...                 ...   
20635       845.0       330.0         1.5603             78100.0   
20636       356.0       114.0         2.5568             77100.0   
20637      1007.0       433.0         1.7000             92300.0   
20638       741.0       349.0         1.8672             84700.0   
20639      1387.0       530.0         2.3886             89400.0   

      ocean_proximity  
0            NEAR BAY  
1            NEAR BAY  
2            NEAR BAY  
3            NEAR BAY  
4            NEAR BAY  
...               ...  
20635          INLAND  
20636          INLAND  
20637          INLAND  
20638          INLAND  
20639          INLAND  

[20640 rows x 10 columns]

In [9]:
df.describe()

longitude      latitude  housing_median_age   total_rooms  \
count  20640.000000  20640.000000        20640.000000  20640.000000   
mean    -119.569704     35.631861           28.639486   2635.763081   
std        2.003532      2.135952           12.585558   2181.615252   
min     -124.350000     32.540000            1.000000      2.000000   
25%     -121.800000     33.930000           18.000000   1447.750000   
50%     -118.490000     34.260000           29.000000   2127.000000   
75%     -118.010000     37.710000           37.000000   3148.000000   
max     -114.310000     41.950000           52.000000  39320.000000   

       total_bedrooms    population    households  median_income  \
count    20433.000000  20640.000000  20640.000000   20640.000000   
mean       537.870553   1425.476744    499.539680       3.870671   
std        421.385070   1132.462122    382.329753       1.899822   
min          1.000000      3.000000      1.000000       0.499900   
25%        296.000000    787.000000    280.000000       2.563400   
50%        435.000000   1166.000000    409.000000       3.534800   
75%        647.000000   1725.000000    605.000000       4.743250   
max       6445.000000  35682.000000   6082.000000      15.000100   

       median_house_value  
count        20640.000000  
mean        206855.816909  
std         115395.615874  
min          14999.000000  
25%         119600.000000  
50%         179700.000000  
75%         264725.000000  
max         500001.000000

#### Question 3: Select columns with missing data

In [49]:
df.isnull().any()

longitude             False
latitude              False
housing_median_age    False
total_rooms           False
total_bedrooms        False
population            False
households            False
median_income         False
median_house_value    False
ocean_proximity       False
dtype: bool

#### Question 4: Number of unique values in the 'ocean_proximity' column
```
5
```


In [33]:
df.ocean_proximity.unique()

array(['NEAR BAY', '<1H OCEAN', 'INLAND', 'NEAR OCEAN', 'ISLAND'],
      dtype=object)

#### Question 5: Average value of the 'median_house_value' for the houses near the bay
```
259212
```

In [24]:
nearbay = df.where(df['ocean_proximity']=='NEAR BAY')
nearbay.median_house_value.mean()


259212.31179039303

#### Question 6: Has the mean value changed after filling missing values?

In [31]:
df.total_bedrooms.mean()

537.8705525375617

In [32]:
df.total_bedrooms.fillna(537.8705525375618, inplace=True)
df.total_bedrooms.mean()

537.8705525375617

#### Questions 7: Value of the last element of w
- 1 Select all the options located on islands.
- 2 
Select only columns housing_median_age, total_rooms, total_bedrooms
- 3 
Get the underlying NumPy array. Let's call it 
- 4 .
Compute matrix-matrix multiplication between the transpose of X and X. To get the transpose, use X.T. Let's call the result X
- 5 X.
Compute the inverse of 
- 6 TX.
Create an array y with v [950,1300,800,1000,1300]1
- 7 00].
Multiply the inverse of XTX with the transpose of X, and then multiply the result by y. Call the res
- lt w.
What's the value of the last elemen w?
```

In [42]:
cols = ['housing_median_age','total_rooms','total_bedrooms']
df_island = df[df['ocean_proximity']=='ISLAND']

X = df_island[cols].to_numpy()
X

array([[  27., 1675.,  521.],
       [  52., 2359.,  591.],
       [  52., 2127.,  512.],
       [  52.,  996.,  264.],
       [  29.,  716.,  214.]])

In [43]:
XT = X.T
XT

array([[  27.,   52.,   52.,   52.,   29.],
       [1675., 2359., 2127.,  996.,  716.],
       [ 521.,  591.,  512.,  264.,  214.]])

In [47]:
XTX = np.dot(XT, X)
XTX
XTX_inv = np.linalg.inv(XTX)
XTX_inv, XTX_inv.sum()

(array([[ 9.19403586e-04, -3.66412216e-05,  5.43072261e-05],
        [-3.66412216e-05,  8.23303633e-06, -2.77534485e-05],
        [ 5.43072261e-05, -2.77534485e-05,  1.00891325e-04]]),
 0.0010083530589819155)

In [48]:
y = [950, 1300, 800, 1000, 1300]

w = np.dot(np.dot(XTX_inv,XT),y)
w

array([23.12330961, -1.48124183,  5.69922946])